### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by T1eerth**
Created README

### CODE REVIEW

**Comment by officialasishkumar** [comment]
Can you add more stuff to the readme? You can reference this repo: https://github.com/prehans/LeetCode-Solution

**Comment by T1eerth** [comment]
Sure man if you give me today's day i would love to make an awesome readme

**Comment by T1eerth** [comment]
> Can you add more stuff to the readme? You can reference this repo: https://github.com/prehans/LeetCode-Solution

Also share your socials i will mention that in the redme too

**Comment by officialasishkumar** [comment]
You can put my discord username: Charon#3571

**Review by T1eerth — COMMENTED** [review]
i have modified the readme file please have a look

**Pull request merged**
